apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: cache.kcp.io
spec:
  resources:
  - group: cache.kcp.io
    name: cachedresourceendpointslices
    schema: v250818-8c393c8d4.cachedresourceendpointslices.cache.kcp.io
    storage:
      crd: {}
  - group: cache.kcp.io
    name: cachedresources
    schema: v250826-966ad80c7.cachedresources.cache.kcp.io
    storage:
      crd: {}
status: {}
