/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	corev1 "k8s.io/api/core/v1"

	v1 "github.com/kcp-dev/kcp/sdk/client/applyconfiguration/meta/v1"
)

// ResourceSchemaStorageVirtualApplyConfiguration represents a declarative configuration of the ResourceSchemaStorageVirtual type for use
// with apply.
type ResourceSchemaStorageVirtualApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	Path                          *string                             `json:"path,omitempty"`
	IdentitySecretRef             *corev1.SecretReference             `json:"identitySecretRef,omitempty"`
	ResourceSelector              *ResourceSelectorApplyConfiguration `json:"resourceSelector,omitempty"`
}

// ResourceSchemaStorageVirtualApplyConfiguration constructs a declarative configuration of the ResourceSchemaStorageVirtual type for use with
// apply.
func ResourceSchemaStorageVirtual() *ResourceSchemaStorageVirtualApplyConfiguration {
	b := &ResourceSchemaStorageVirtualApplyConfiguration{}
	b.WithKind("ResourceSchemaStorageVirtual")
	b.WithAPIVersion("apis.kcp.io/v1alpha2")
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ResourceSchemaStorageVirtualApplyConfiguration) WithKind(value string) *ResourceSchemaStorageVirtualApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ResourceSchemaStorageVirtualApplyConfiguration) WithAPIVersion(value string) *ResourceSchemaStorageVirtualApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ResourceSchemaStorageVirtualApplyConfiguration) WithPath(value string) *ResourceSchemaStorageVirtualApplyConfiguration {
	b.Path = &value
	return b
}

// WithIdentitySecretRef sets the IdentitySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentitySecretRef field is set to the value of the last call.
func (b *ResourceSchemaStorageVirtualApplyConfiguration) WithIdentitySecretRef(value corev1.SecretReference) *ResourceSchemaStorageVirtualApplyConfiguration {
	b.IdentitySecretRef = &value
	return b
}

// WithResourceSelector sets the ResourceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceSelector field is set to the value of the last call.
func (b *ResourceSchemaStorageVirtualApplyConfiguration) WithResourceSelector(value *ResourceSelectorApplyConfiguration) *ResourceSchemaStorageVirtualApplyConfiguration {
	b.ResourceSelector = value
	return b
}
