/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CachedResourceSchemaApplyConfiguration represents a declarative configuration of the CachedResourceSchema type for use
// with apply.
type CachedResourceSchemaApplyConfiguration struct {
	APIResourceSchema *APIResourceSchemaReferenceApplyConfiguration `json:"apiResourceSchema,omitempty"`
	CRD               *CRDReferenceApplyConfiguration               `json:"crd,omitempty"`
}

// CachedResourceSchemaApplyConfiguration constructs a declarative configuration of the CachedResourceSchema type for use with
// apply.
func CachedResourceSchema() *CachedResourceSchemaApplyConfiguration {
	return &CachedResourceSchemaApplyConfiguration{}
}

// WithAPIResourceSchema sets the APIResourceSchema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIResourceSchema field is set to the value of the last call.
func (b *CachedResourceSchemaApplyConfiguration) WithAPIResourceSchema(value *APIResourceSchemaReferenceApplyConfiguration) *CachedResourceSchemaApplyConfiguration {
	b.APIResourceSchema = value
	return b
}

// WithCRD sets the CRD field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CRD field is set to the value of the last call.
func (b *CachedResourceSchemaApplyConfiguration) WithCRD(value *CRDReferenceApplyConfiguration) *CachedResourceSchemaApplyConfiguration {
	b.CRD = value
	return b
}
