/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CachedAPIResourceSchemaApplyConfiguration represents a declarative configuration of the CachedAPIResourceSchema type for use
// with apply.
type CachedAPIResourceSchemaApplyConfiguration struct {
	Name         *string `json:"name,omitempty"`
	UID          *string `json:"UID,omitempty"`
	Cluster      *string `json:"cluster,omitempty"`
	IdentityHash *string `json:"identityHash,omitempty"`
}

// CachedAPIResourceSchemaApplyConfiguration constructs a declarative configuration of the CachedAPIResourceSchema type for use with
// apply.
func CachedAPIResourceSchema() *CachedAPIResourceSchemaApplyConfiguration {
	return &CachedAPIResourceSchemaApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CachedAPIResourceSchemaApplyConfiguration) WithName(value string) *CachedAPIResourceSchemaApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *CachedAPIResourceSchemaApplyConfiguration) WithUID(value string) *CachedAPIResourceSchemaApplyConfiguration {
	b.UID = &value
	return b
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *CachedAPIResourceSchemaApplyConfiguration) WithCluster(value string) *CachedAPIResourceSchemaApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithIdentityHash sets the IdentityHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdentityHash field is set to the value of the last call.
func (b *CachedAPIResourceSchemaApplyConfiguration) WithIdentityHash(value string) *CachedAPIResourceSchemaApplyConfiguration {
	b.IdentityHash = &value
	return b
}
